# Download YCSB and extract. Then install java
- name: download ycsb
  shell: curl -O --location https://github.com/brianfrankcooper/YCSB/releases/download/0.15.0/ycsb-0.15.0.tar.gz

- name: extract ycsb
  shell: tar xfvz ycsb-0.15.0.tar.gz

- name: Install basic utilities debian
  tags:
   - configuration
  apt: name={{ item }} state=present update_cache=yes
  with_items:
   - default-jre
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

