# Launch instances, wait for ssh, apply minimal and common roles and add to monitoring

- name: Create a spot instance request
  hosts: localhost
  gather_facts: False
  tasks:
    - name: query api
      ec2_ami_facts:
        filters:
          "name": "ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-*"
      register: amis
    - name: sort by creation date
      set_fact:
        sorted_amis: "{{ amis.images | sort(attribute='creation_date') }}"
    - name: get latest
      set_fact:
        latest_ami: "{{ sorted_amis | last }}"

    - name: Launch instance
      ec2:
         key_name: recsys
         group: "Internal Access"
         instance_type: "{{ instance_type | default('t2.micro') }}"
         image: ami-08d658f84a6d84a80
                #"{{ latest_ami.image_id }}"
         count: "{{ count | default('1') }}"
         wait: yes
         wait_timeout: 500
         region: "{{ region | default('eu-west-1') }}"
         spot_price: "{{ spot_price | default('0.1') }}"
         spot_wait_timeout: 600
         ebs_optimized: yes
         volumes:
           - device_name: /dev/sda1
             volume_type: gp2
             volume_size: "{{ volume_size | default('20') }}"
             delete_on_termination: yes
         instance_tags:
           Name: "{{ Name }}"
         vpc_subnet_id: subnet-c70a86b0
      register: ec2

    - name: Create target directory
      file:
        path: target
        state: directory
        mode: 0755

    - name: Add instance it to the target
      copy:
        content: "{{ ec2.instance_ids }}"
        dest: target/instance

    - name: Add instance hostname target
      copy:
        content: "{{ Name }}"
        dest: target/hostname

    - name: Add new instance to ec2 group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: ec2
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_ip }}"
        port: 22
        delay: 20
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"

    - name: refresh inventory
      meta: refresh_inventory
