---
- hosts: "{{ variable_host | default('all') }}"
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - prometheus_node_exporter

- hosts: 63.35.169.196
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - prometheus
    - grafana
