---
- hosts: "{{ variable_host | default('all') }}"
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - prometheus_node_exporter

- hosts: localhost
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - prometheus
    - grafana
